sudo: required
#Sudo means - it instructs travis to provide super use to our container
service:
   - docker
before_install:
   - docker build -f Dockerfile.dev -t afrozjava/afreen .
script:
   - docker run -e CI=true afrozjava/afreen npm run test -- --coverage

# added following code to perform automated deployment from Travis CI to AWS 
deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'Docker'
  env: '	Docker-env-1'
  bucket_name: 'elasticbeanstalk-ap-south-1-246453948081'
  bucket_path: 'Docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY